### PR TITLE
Integrate GK cert as the default internal cert

### LINKED ISSUE #653: HNC: let HNC run without cert-manager
We've had some discussions at Google about HNC, and some of us were concerned by the runtime dependency on `cert-manager`. For example, we've already seen cases where different versions of `cert-manager` can break us - what happens if someone has the wrong version installed on their cluster? 

By contrast, Gatekeeper is a similar project to HNC, but has the optional ability to generate its own [self-signed certs for its webhooks](https://github.com/open-policy-agent/gatekeeper/blob/master/pkg/webhook/certs.go). We thought it would be nice to include this capability in HNC as well.

We had a chat with the `controller-runtime` folks about moving Gatekeeper's cert management there, but they're not really interested in maintaining it. For now, the best solution we can think of is simply to copy Gatekeeper's manager (which is a single code file, plus a test file) into HNC, and update it periodically with fixes. @yiqigao217 has already been working with Gatekeeper to get some (unrelated) fixes into their cert manager so she has a good understanding of how that code works.

Hopefully this is an interim solution until we move that file to a proper library location, but in the meantime, we think this will make HNC easier to use in more environments.

### PR DESCRIPTION
**Pull request by yiqigao217**
Fork the cert management from open-policy-agent/gatekeeper repo to serve
as the default internal cert management for HNC.

Add an "enable-internal-cert-management" flag to switch between using
the internal cert (integrated Gatekeeper cert) or the external cert
"cert-manager".

Update main.go to start the controller manager with internal certs first
and once the cert files are ready, add other controllers and webhooks if
webhook is enabled and internal certs are used.

Refactor the cert generation and validator startup into
pkg/validators/setup.go.

To use external cert-manager, update config/default/kustomization.yaml
and manager_auth_proxy_patch.yaml as instructed. Run 'make deploy-cm'
before 'make deploy'.

Tested on a GKE cluster. The manager restarts 0 times and the webhooks
are working as expected.

Fixes #653

### CODE REVIEW

File: incubator/hnc/Makefile [hunk 1]
```diff
@@ -128,14 +135,14 @@ endif
...
-deploy: deploy-prereq docker-push kubectl manifests
+deploy: docker-push kubectl manifests
 	-kubectl -n hnc-system delete deployment hnc-controller-manager
 	kubectl apply -f manifests/hnc-manager.yaml
 
 deploy-watch:
 	kubectl logs -n hnc-system --follow deployment/hnc-controller-manager manager
 
-# Installs prerequisites. See https://cert-manager.io/docs/installation/kubernetes/ for why we're not validating our YAML.
+# Installs external certs before deploying HNC. See https://cert-manager.io/docs/installation/kubernetes/ for why we're not validating our YAML.
```
Comment (adrianludwin) [inline incubator/hnc/Makefile:145]: Maybe change to deploy-cm, since that's now all it does? They're not really prereqs anymore

File: incubator/hnc/cmd/manager/main.go [hunk 2]
```diff
@@ -131,6 +150,41 @@ func main() {
 		os.Exit(1)
 	}
 
+	// Make sure certs are generated and valid if cert rotation is enabled.
```
Comment (adrianludwin) [inline incubator/hnc/cmd/manager/main.go:153]: Maybe move this to its own function? main() is getting very long

File: incubator/hnc/config/default/kustomization.yaml [hunk 3]
```diff
@@ -17,7 +17,8 @@ bases:
 - ../rbac
 - ../manager
 - ../webhook
-- ../certmanager
```
Comment (adrianludwin) [inline incubator/hnc/config/default/kustomization.yaml:20]: Comment this out rather than remove it completely? Likewise below

File: incubator/hnc/config/oldDefaultExternalCert/kustomization.yaml [hunk 4]
```diff
@@ -0,0 +1,67 @@
+# Adds namespace to all resources.
```
Comment (adrianludwin) [inline incubator/hnc/config/oldDefaultExternalCert/kustomization.yaml:1]: Rather than duplicate all these files, for now I'd just comment out the relevant parts in the main one. That's what kubebuilder gives us in the first place.

File: incubator/hnc/config/default/kustomization.yaml [hunk 5]
```diff
@@ -17,7 +17,10 @@ bases:
...
+# Add cert management. Only one of the ../internalcert and the
+# ../certmanager should be enabled.
```
Comment (adrianludwin) [inline incubator/hnc/config/default/kustomization.yaml:21]: Also mention where `--enable-internal-cert-management` should be added or removed.

File: incubator/hnc/config/default/manager_auth_proxy_patch.yaml [hunk 6]
```diff
@@ -26,3 +26,4 @@ spec:
         - "--leader-election-id=hnc-controller-leader-election-helper"
         - "--max-reconciles=10"
         - "--apiserver-qps-throttle=50"
+        - "--enable-internal-cert-management=true"
```
Comment (adrianludwin) [inline incubator/hnc/config/default/manager_auth_proxy_patch.yaml:29]: Do we need this line in any other yaml file? Eg I think this list of arguments is included in another file too.

Comment (yiqigao217) [reply incubator/hnc/config/default/manager_auth_proxy_patch.yaml:29]: I don't think so. I just double checked the PRs [1](https://github.com/kubernetes-sigs/multi-tenancy/commit/29c17f2757803f0e28e07e99ceaba0f1c59b57e2), [2](https://github.com/kubernetes-sigs/multi-tenancy/pull/377/commits/39010d8bb51978fc392e5e99b2c56e86292d5c14) for `max-reconciles` and `apiserver-qps-throttle` to confirm that they are only used here.

File: incubator/hnc/config/default/kustomization.yaml (hunk 5 above)
Comment (yiqigao217) [reply incubator/hnc/config/default/kustomization.yaml]: Good point! Done, thanks!

File: incubator/hnc/config/default/manager_auth_proxy_patch.yaml (hunk 6 above)
Comment (adrianludwin) [reply incubator/hnc/config/default/manager_auth_proxy_patch.yaml:29]: sgtm, thanks for checking.
