### PR TITLE
Fix the flaky test for #716

### LINKED ISSUE #950: HNC: e2e test flake
Skipping setup/teardown commands:

```
• Failure [32.979 seconds]
Issues
/usr/local/google/home/aludwin/git/multi-tenancy/incubator/hnc/test/e2e/issues_test.go:9
  Should not delete a non-leaf subnamespace if allowCascadingDelete is not set - issue #716 [It]
  /usr/local/google/home/aludwin/git/multi-tenancy/incubator/hnc/test/e2e/issues_test.go:190

  Expected
      <nil>: nil
  not to be nil

  /usr/local/google/home/aludwin/git/multi-tenancy/incubator/hnc/test/e2e/e2e_test.go:37
------------------------------
<... setup omittted...>
Running:  [kubectl create ns parent]
Output:  namespace/parent created

Running:  [kubectl hns create child -n parent]
Output:  Successfully created "child" subnamespace anchor in "parent" namespace

Running:  [kubectl hns create sub-child -n child]
Output:  Successfully created "sub-child" subnamespace anchor in "child" namespace

Running:  [kubectl delete subns child -n parent]
Output:  subnamespaceanchor.hnc.x-k8s.io "child" deleted

<... teardown omittted...>
```

/assign @GinnyJI 

Perhaps we're deleting `child` before the namespace `sub-child` has been created (we're allowed to delete an anchor if it doesn't have a namespace, I _think_). Can you confirm that this is the intended behaviour and, if so, find a way to fix this? Thanks!

### PR DESCRIPTION
**Pull request by GinnyJI**
Change the mustNotRun() function to use Eventually() so that we get
stable test result. Add sleep time after create subnamespace so that the
anchor is ready before test. Change the default wait time in mustRun()
and mustNotRun() to 5 seconds because deleting a subnamespace takes a
while.

Tested: make e2e-test

Fix #950

### CODE REVIEW

**Comment by GinnyJI** [comment]
> lgtm just a minor typo in the commit/PR message "deletign"

done

File: incubator/hnc/test/e2e/issues_test.go [hunk 1]
```diff
@@ -194,6 +194,8 @@ var _ = Describe("Issues", func() {
 		mustRun("kubectl hns create", nsSubChild, "-n", nsChild)
 		// Test: remove non-leaf subnamespace with 'allowCascadingDelete' unset.
 		// Expected: forbidden because 'allowCascadingDelete'flag is not set
+		// wait 2 seconds for the sub-child namespace to be created 
+		time.Sleep(2*time.Second)
```
Comment (adrianludwin) [inline incubator/hnc/test/e2e/issues_test.go:198]: Sleeps are usually the wrong way to solve a problem - if we're waiting for the namespace to be created, can you make that explicit?

File: incubator/hnc/test/e2e/e2e_test.go [hunk 2]
```diff
@@ -29,12 +29,13 @@ func TestE2e(t *testing.T) {
 func mustRun(cmdln ...string) {
 	Eventually(func() error {
 		return tryRun(cmdln...)
-	}, 2).Should(BeNil())
+	}, 5).Should(BeNil())
```
[the remark this answers is not in the document]
Comment (GinnyJI) [reply incubator/hnc/test/e2e/e2e_test.go]: done

File: incubator/hnc/test/e2e/issues_test.go (hunk 1 above)
Comment (GinnyJI) [reply incubator/hnc/test/e2e/issues_test.go]: done
