### PR TITLE
fix Canonical function

### LINKED ISSUE #238: HNC: Canonical function will fail for tree labels
The current approach only catches HNC-related labels/annotations with prefix `api.MetaGroup`, so the tree labels (i.e. `namespace.tree.hnc.x-k8s.io/depth` doesn't have `api.MetaGroup` as prefix) will remain in the canocial copy of an object, which is not the expected behaviour.

### PR DESCRIPTION
**Pull request by lafh**
Currently the tree label will stay in the canocial version of the object

/resolve #238

### CODE REVIEW

**Comment by lafh** [comment]
assign @adrianludwin

File: incubator/hnc/pkg/object/object.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func Canonical(inst *unstructured.Unstructured) *unstructured.Unstructured {
 	// Non-HNC annotations:
 	newAnnots := map[string]string{}
 	for k, v := range inst.GetAnnotations() {
-		if !strings.HasPrefix(k, api.MetaGroup) {
+		if !strings.Contains(k, api.MetaGroup) {
```
Comment (adrianludwin) [inline incubator/hnc/pkg/object/object.go]: I don't think this is the right logic. While it's unlikely, `hnc.x-k8s.io.foo/bar` is actually fine, and shouldn't be stripped out. Maybe add this as a test case too?

Comment (lafh) [reply incubator/hnc/pkg/object/object.go]: sg.

File: incubator/hnc/pkg/object/object.go [hunk 2]
```diff
@@ -35,7 +36,9 @@ func Canonical(inst *unstructured.Unstructured) *unstructured.Unstructured {
 	// Non-HNC labels:
 	newLabels := map[string]string{}
 	for k, v := range inst.GetLabels() {
-		if !strings.HasPrefix(k, api.MetaGroup) {
+		if !strings.HasPrefix(k, api.MetaGroup) &&
```
Comment (adrianludwin) [inline incubator/hnc/pkg/object/object.go]: This will break if we add any other prefixes like `tree`. How about something like:

```
if !strings.HasSuffix(metaPrefix(k), api.MetaGroup) { ... }

...

func metaPrefix(s string) string {
  p := strings.Split(s, "/")
  if len(p) == 1 {
    return ""
  }
  return p[0]
}
```

Comment (adrianludwin) [reply incubator/hnc/pkg/object/object.go]: Reference: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
