### PR TITLE
Propagate empty source object to descendants if the descendants do not have not copy of the object.

### LINKED ISSUE #441: HNC: Empty source object cannot be propagated by object reconciler
Current object reconciler will only propagate an object when a descendant's copy of the object is different from the source object. This is currently handled in [syncPropagated](https://github.com/kubernetes-sigs/multi-tenancy/blob/95218a0fb87fee9d024202ad9a4e1755d9964b56/incubator/hnc/pkg/controllers/object_controller.go#L222) method.  

However, when source object is empty (but not nil) and when a descendant does not have any copy of the object, syncPropagated will return ["ignore"](https://github.com/kubernetes-sigs/multi-tenancy/blob/95218a0fb87fee9d024202ad9a4e1755d9964b56/incubator/hnc/pkg/controllers/object_controller.go#L227) action and will not propagate the empty object to the descendant. When source object is not nil and when a descendant does not have any copy of the object, we would expect the object to be propagated to the descendant, even when the object is empty.

To reproduce this issue:
* Create acme-org, team-a namespaces. Set team-a as child of acme-org
     * kubectl create namespace acme-org
     * kubectl create namespace team-a
     * kubectl hns set team-a --parent  acme-org
* Create an empty and an non-empty configmaps in acme-org
     * kubectl -n acme-org create cm emptycf
     * kubectl -n acme-org create cm nonemptycf --from-literal key=value
* Check that acme-org has two configmaps and team-a does not have any configmap
     * kubectl get cm -n acme-org
     * kubectl get cm -n team-a
* Add ConfigMap in HNCConfiguration
     * kubectl get hncconfiguration config -o yaml > hncconfig.yaml
     * Add following in hncconfig.yaml
          - apiVersion: v1
             kind: ConfigMap
             mode: propagate
     * kubectl apply -f hncconfig.yaml
* Now you will see team-a has nonemptycf but does not have emptycf
     * kubectl get cm -n team-a

### PR DESCRIPTION
**Pull request by sophieliu15**
Currently an empty source object will not be propagated to descendants if the descendants do not have any copy of the object as reported in #441. The PR fixes this issue so that empty source object will be propagated to descendants if the descendants do not have the copy of the object.

Fixes #441

### CODE REVIEW

File: incubator/hnc/pkg/controllers/object_controller.go [hunk 1]
```diff
@@ -218,6 +218,14 @@ func (r *ObjectReconciler) syncPropagated(ctx context.Context, log logr.Logger,
 		return remove, nil
 	}
 
+	// If an object doesn't exist, assume it's been deleted or not yet created. In this case, we will
+	// return write action and the source instance.
+	exist := inst.GetCreationTimestamp() != v1.Time{}
```
Comment (adrianludwin) [inline incubator/hnc/pkg/controllers/object_controller.go]: See if `inst.GetCreationTimestamp().IsZero()` works here. I don't think we ever figured out why it sometimes works but sometimes wouldn't compile.

File: incubator/hnc/pkg/controllers/object_controller.go [hunk 2]
```diff
@@ -218,6 +218,14 @@ func (r *ObjectReconciler) syncPropagated(ctx context.Context, log logr.Logger,
...
+	if !exist {
+		metadata.SetLabel(inst, api.LabelInheritedFrom, srcInst.GetNamespace())
```
Comment (adrianludwin) [inline incubator/hnc/pkg/controllers/object_controller.go]: In order to avoid calling SetLabel twice, maybe merge the two `if` statements?

File: incubator/hnc/pkg/controllers/config_controller_test.go [hunk 3]
```diff
@@ -52,6 +54,29 @@ var _ = Describe("HNCConfiguration", func() {
 		Eventually(hasSecret(ctx, barName, "foo-sec")).Should(BeTrue())
 		Expect(secretInheritedFrom(ctx, barName, "foo-sec")).Should(Equal(fooName))
 	})
+
+	It("should propagate an empty object whose types have been added to HNCConfiguration", func() {
```
Comment (adrianludwin) [inline incubator/hnc/pkg/controllers/config_controller_test.go]: Ideally this would be in object-controller-test, since it's only testing a pure feature of the object controller? Would it be possible to move this there?

File: incubator/hnc/pkg/controllers/config_controller_test.go [hunk 4]
```diff
@@ -52,6 +54,29 @@ var _ = Describe("HNCConfiguration", func() {
...
+		Eventually(hasConfigMap(ctx, barName, "foo-config")).Should(BeFalse())
+
+		Eventually(func() error {
+			c := getHNCConfig(ctx)
+			return addConfigMapToHNCConfig(ctx, c)
+		}).Should(Succeed())
+
+		// "foo-config" should now be propagated from foo to bar.
+		Eventually(hasConfigMap(ctx, barName, "foo-config")).Should(BeTrue())
+		Expect(configMapInheritedFrom(ctx, barName, "foo-config")).Should(Equal(fooName))
```
Comment (adrianludwin) [inline incubator/hnc/pkg/controllers/config_controller_test.go]: This is the only "real" part of this test - everything else is tested elsewhere. Maybe create a helper to add ConfigMaps as a supported type in the object controller (e.g. change `addConfigMapToHNCConfig` to include the whole `Eventually` and `getHNCCConfig` stuff) so you can call it from object-controller-test, and skip the stuff where you try to propagate _before_ creating the object controller, since you already test that.

Comment (sophieliu15) [reply incubator/hnc/pkg/controllers/config_controller_test.go]: Thanks for the suggestion! PTAL

File: incubator/hnc/pkg/controllers/config_controller_test.go (hunk 3 above)
Comment (sophieliu15) [reply incubator/hnc/pkg/controllers/config_controller_test.go]: Good idea. Moved to the object_controller_test.go. Also moved some more shared functions to the test_helpers_test.go

File: incubator/hnc/pkg/controllers/object_controller.go (hunk 2 above)
Comment (sophieliu15) [reply incubator/hnc/pkg/controllers/object_controller.go]: Thanks for the suggestion! Done.

File: incubator/hnc/pkg/controllers/object_controller.go (hunk 1 above)
Comment (sophieliu15) [reply incubator/hnc/pkg/controllers/object_controller.go]: Looks like it still doesn't work. It has compile errors:
pkg/controllers/object_controller.go:224:38: cannot call pointer method on inst.GetCreationTimestamp()
pkg/controllers/object_controller.go:224:38: cannot take the address of inst.GetCreationTimestamp()

Comment (adrianludwin) [reply incubator/hnc/pkg/controllers/object_controller.go]: Ah well, worth a shot.

File: incubator/hnc/pkg/controllers/object_controller_test.go [hunk 5]
```diff
@@ -48,6 +55,18 @@ var _ = Describe("Secret", func() {
 		Expect(roleInheritedFrom(ctx, bazName, "bar-role")).Should(Equal(barName))
 	})
 
+	It("should be copied to descendents when source object is empty", func() {
+		setParent(ctx, barName, fooName)
+		// Creates an empty ConfigMap. We use ConfigMap for this test because the apiserver will not
+		// add additional fields to an empty ConfigMap object to make it non-empty.
+		makeConfigMap(ctx, fooName, "foo-config")
+		addConfigMapToHNCConfig(ctx)
```
[the remark this answers is not in the document]
Comment (sophieliu15) [reply incubator/hnc/pkg/controllers/object_controller_test.go]: Thanks for the suggestion! Will do!
