### PR TITLE
Fix E2E tests and namespace deletion validation

### LINKED ISSUE #1269: HNC:E2E tests failing
I checked out the latest master branch for HNC and tried running the e2e tests. There seem to a lot of failures with the messages

[1605319933] Running:  [kubectl delete ns recover-test-a]
Output (failed):  Error: exit status 1
Output: Error from server (Forbidden): admission webhook "namespaces.hnc.x-k8s.io" denied the request: Please set allowCascadingDeletion in the parent namespace.

If i switch to the release branch hnc-v0.6  they all seem to pass. It seems this is related to this recent commit - https://github.com/kubernetes-sigs/multi-tenancy/commit/d2914ca100499ccc7590ac6c6bc81dc299e1a55d 

Any suggestions to get around this or any pointers of what needs to fixed (if any) in the tests.?
I was trying to pickup one of the "good first issue" issues to work on where I ran into this error.

### PR DESCRIPTION
**Pull request by GinnyJI**
When deleting a parent namespace, we should allow it if none of its
children are sub-namespace.

In the E2E test, I moved the webhook deletion out of AfterEach, so that
if the user doesn't have HNC_REPAIR path set, it won't delete the
webhook.

Since we changed the deletion validator, one of the tests for issue #716
does not apply anymore. I deleted it in this PR.

Fix #1269

Tested: make test-e2e

### CODE REVIEW

File: incubator/hnc/internal/validators/namespace.go [hunk 1]
```diff
@@ -137,7 +137,17 @@ func (v *Namespace) cannotDeleteSubnamespace(req *nsRequest) admission.Response
 }
 
 func (v *Namespace) illegalCascadingDeletion(ns *forest.Namespace) admission.Response {
-	if ns.AllowsCascadingDeletion() || len(ns.ChildNames()) == 0 {
+	if ns.AllowsCascadingDeletion() {
+		return allow("")
+	}
+
+	subNs := []string{}
```
Comment (adrianludwin) [inline incubator/hnc/internal/validators/namespace.go:144]: Do we need to build a list? Or can we just return as soon as we find the first subnamespace?

File: incubator/hnc/pkg/testutils/testutils.go [hunk 2]
```diff
@@ -260,6 +260,11 @@ func CleanupNamespaces(nses ...string) {
 		// TODO: remove this line after v0.6 branches and we are no longer supporting v1alpha1
 		// conversion.
 		MustRunWithTimeout(cleanupTimeout, "kubectl annotate ns", ns, "hnc.x-k8s.io/subnamespaceOf-")
+
+		// If it has `ParentMissing` condition, set it as the root namespace
+		MustRun("kubectl hns set --root", ns)
+		// If this is a parent namespace, set allowCascadingDelete 
+		MustRun("kubectl hns set", ns, "-a")
```
Comment (adrianludwin) [inline incubator/hnc/pkg/testutils/testutils.go:267]: Do we still need any of this? Now that you've fixed the behaviour of allowCascadingDeletion, we shoudn't need to set it here because we ensure that there aren't any subnamespaces left. And namespaces don't have to be roots to be deleted.

File: incubator/hnc/test/e2e/delete_crd_test.go [hunk 3]
```diff
@@ -20,11 +20,6 @@ var _ = Describe("When deleting CRDs", func() {
 	})
 
 	AfterEach(func() {
-		// HNC might be in an arbitrarily bad state - e.g. the CRDs are gone so the reconcilers aren't
-		// running anymore, and the admission webhooks are operating off of bad information (e.g. that a
-		// subnamespace's annotation has been removed). So delete the VWC so we can clean up
-		// effectively; it'll be restored by RecoverHNC anyway.
-		MustRun("kubectl delete validatingwebhookconfigurations hnc-validating-webhook-configuration")
```
Comment (adrianludwin) [inline incubator/hnc/test/e2e/delete_crd_test.go:27]: No, we still need this here! Because if the test fails, we won't get to the end of the test to clean up properly. All cleanup *must* be in AfterEach.

But we should check to see if HNC_REPAIR is set and skip this line if it's not.

File: incubator/hnc/test/e2e/issues_test.go [hunk 4]
```diff
@@ -150,7 +150,7 @@ var _ = Describe("Issues", func() {
 		RunShouldContain("ActivitiesHalted (AncestorHaltActivities)", defTimeout, "kubectl hns describe", nsSubChild)
 	})
 
-	It("Should have ParentMissing condition when parent namespace is deleted - issue #716", func() {
+	It("Should have ParentMissing condition when root namespace is deleted - issue #716", func() {
```
Comment (adrianludwin) [inline incubator/hnc/test/e2e/issues_test.go:153]: Why this change?

File: incubator/hnc/test/e2e/issues_test.go [hunk 5]
```diff
@@ -161,18 +161,6 @@ var _ = Describe("Issues", func() {
 		RunShouldContain("ActivitiesHalted (ParentMissing)", defTimeout, "kubectl hns describe", nsChild)
 	})
 
-	It("Should delete namespace with ParentMissing condition - issue #716", func() {
```
Comment (adrianludwin) [inline incubator/hnc/test/e2e/issues_test.go:164]: Why did you remove this?

File: incubator/hnc/test/e2e/issues_test.go (hunk 4 above)
Comment (GinnyJI) [reply incubator/hnc/test/e2e/issues_test.go:153]: I _feel_ like the parent namespace kind of refers to the parent-subnamespace scenario. Is there a way to differentiate it with the parent-child(not subnamespace) case?

File: incubator/hnc/test/e2e/issues_test.go (hunk 5 above)
Comment (GinnyJI) [reply incubator/hnc/test/e2e/issues_test.go:164]: I looked at issue #716 and feel like it's not relevant anymore?

File: incubator/hnc/test/e2e/delete_crd_test.go (hunk 3 above)
Comment (GinnyJI) [reply incubator/hnc/test/e2e/delete_crd_test.go:27]: Got it! Done

File: incubator/hnc/pkg/testutils/testutils.go (hunk 2 above)
Comment (GinnyJI) [reply incubator/hnc/pkg/testutils/testutils.go:267]: You are right, removed

File: incubator/hnc/internal/validators/namespace.go (hunk 1 above)
Comment (GinnyJI) [reply incubator/hnc/internal/validators/namespace.go:144]: Done

File: incubator/hnc/internal/validators/namespace.go [hunk 6]
```diff
@@ -137,7 +137,17 @@ func (v *Namespace) cannotDeleteSubnamespace(req *nsRequest) admission.Response
...
+
+	hasSubNs := false
+	for _, cnm := range ns.ChildNames() {
+		if v.Forest.Get(cnm).IsSub {
+			hasSubNs = true
+		}
+	}
+	if !hasSubNs {
 		return allow("")
 	}
```
Comment (adrianludwin) [inline incubator/hnc/internal/validators/namespace.go:152]: This could be even simpler:

```
for _, cnm := range ns.ChildNames() {
  if v.Forest.Get(cnm).IsSub {
    msg := "This namespaces contains subnamespaces. Please remove all subnamespaces before deleting this namespace, or set 'allowCascadingDeletion' to delete them automatically."
    return deny(metav1.StatusReasonForbidden, msg)
  }
}

return allow("no subnamespaces found")
```

File: incubator/hnc/pkg/testutils/testutils.go [hunk 7]
```diff
@@ -260,6 +260,9 @@ func CleanupNamespaces(nses ...string) {
 		// TODO: remove this line after v0.6 branches and we are no longer supporting v1alpha1
 		// conversion.
 		MustRunWithTimeout(cleanupTimeout, "kubectl annotate ns", ns, "hnc.x-k8s.io/subnamespaceOf-")
+
+		// If it has `ParentMissing` condition, set it as the root namespace
+		MustRun("kubectl hns set --root", ns)
```
Comment (adrianludwin) [inline incubator/hnc/pkg/testutils/testutils.go:265]: Why?

File: incubator/hnc/test/e2e/issues_test.go (hunk 5 above)
Comment (adrianludwin) [reply incubator/hnc/test/e2e/issues_test.go:164]: sgtm

File: incubator/hnc/internal/validators/namespace.go (hunk 6 above)
Comment (yiqigao217) [reply incubator/hnc/internal/validators/namespace.go:152]: +1

File: incubator/hnc/pkg/testutils/testutils.go (hunk 7 above)
Comment (yiqigao217) [reply incubator/hnc/pkg/testutils/testutils.go:265]: +1

File: incubator/hnc/internal/validators/namespace.go (hunk 6 above)
Comment (GinnyJI) [reply incubator/hnc/internal/validators/namespace.go:152]: done

File: incubator/hnc/pkg/testutils/testutils.go (hunk 7 above)
Comment (GinnyJI) [reply incubator/hnc/pkg/testutils/testutils.go:265]: sry I thought I have deleted

**Review by adrianludwin — COMMENTED** [review]
/lgtm
/approve
