### PR TITLE
Ensure hierarchy doesn't violate required children

### LINKED ISSUE #99: HNC: ensure hierarchy doesn't violate required children
Once #90 is complete, we should add a validating webhook to ensure that required children are not reassigned to the wrong parents.

/good-first-issue

### PR DESCRIPTION
**Pull request by yiqigao217**
This validates required child and parent of a required children. It will close #99 .

Tested manually first by setting parent of a required child and setting
different NS as required child. Then unit tests are added.

### CODE REVIEW

File: incubator/hnc/pkg/validators/hierarchy.go [hunk 1]
```diff
@@ -151,13 +166,40 @@ func (v *Hierarchy) checkForest(hc *api.HierarchyConfiguration) ([]authzReq, adm
...
 	// parent conflicts with something in the _existing_ hierarchy.
 	if reason := ns.CanSetParent(newParent); reason != "" {
-		return nil, deny(metav1.StatusReasonConflict, "Illegal parent: "+reason)
+		return deny(metav1.StatusReasonConflict, "Illegal parent: "+reason)
 	}
 
-	// TODO: requiredChild check: https://github.com/kubernetes-sigs/multi-tenancy/issues/99
+	// Prevent changing parent of a required child
+	if ns.RequiredChildOf != "" && ns.RequiredChildOf != newParent.Name() {
+		reason := fmt.Sprintf("Cannot set the parent of %q to %q because it's required child of %q", ns.Name(), newParent.Name(), ns.RequiredChildOf)
```
Comment (adrianludwin) [inline incubator/hnc/pkg/validators/hierarchy.go]: because it's **a** required child

File: incubator/hnc/pkg/validators/hierarchy.go [hunk 2]
```diff
@@ -151,13 +166,40 @@ func (v *Hierarchy) checkForest(hc *api.HierarchyConfiguration) ([]authzReq, adm
...
+			return deny(metav1.StatusReasonConflict, "Illegal requiredChild: "+reason)
+		}
+		if cns.Parent() != nil && cns.Parent() != ns {
+			reason := fmt.Sprintf("Cannot set %q as the required child of %q because it's already a child of %q", cns.Name(), ns.Name(), cns.Parent().Name())
+			return deny(metav1.StatusReasonConflict, "Illegal requiredChild: "+reason)
+		}
+		if cns.Parent() == nil {
+			reason := fmt.Sprintf("Cannot set %q as the required child of %q because it's a root", cns.Name(), ns.Name())
+			return deny(metav1.StatusReasonConflict, "Illegal requiredChild: "+reason)
+		}
```
Comment (adrianludwin) [inline incubator/hnc/pkg/validators/hierarchy.go]: Should we replace all of these with "because it already exists and is not a child of X"?

File: incubator/hnc/pkg/validators/hierarchy.go [hunk 3]
```diff
@@ -151,13 +166,40 @@ func (v *Hierarchy) checkForest(hc *api.HierarchyConfiguration) ([]authzReq, adm
...
-	return v.needAuthzOn(curParent, newParent), allow("")
+	return allow("")
+}
+
+func (v *Hierarchy) checkRequiredChildren(ns *forest.Namespace, requiredChildren []string) admission.Response {
+	for _, child := range requiredChildren {
+		cns := v.Forest.Get(child)
+		// Early exit if we find the newly-added requiredChild
+		if !cns.Exists() {
+			return allow("RequiredChild namesapce is just created")
```
Comment (adrianludwin) [inline incubator/hnc/pkg/validators/hierarchy.go]: s/namesapce/namespace/

Comment (yiqigao217) [reply incubator/hnc/pkg/validators/hierarchy.go]: Do you mean specify the name of the RequiredChild here?

**Comment by adrianludwin** [comment]
No just that there's a typo 🙂

File: incubator/hnc/pkg/validators/hierarchy.go (hunk 3 above)
Comment (adrianludwin) [reply incubator/hnc/pkg/validators/hierarchy.go]: No just that there was a typo :)

File: incubator/hnc/pkg/validators/hierarchy.go [hunk 4]
```diff
@@ -151,13 +166,32 @@ func (v *Hierarchy) checkForest(hc *api.HierarchyConfiguration) ([]authzReq, adm
...
-	return v.needAuthzOn(curParent, newParent), allow("")
+	return allow("")
+}
+
+func (v *Hierarchy) checkRequiredChildren(ns *forest.Namespace, requiredChildren []string) admission.Response {
+	for _, child := range requiredChildren {
+		cns := v.Forest.Get(child)
+		// Early exit if we find the newly-added requiredChild
+		if !cns.Exists() {
+			return allow("RequiredChild namespace is just created")
```
Comment (adrianludwin) [inline incubator/hnc/pkg/validators/hierarchy.go]: Whoops this should just be a `continue`, we don't want to short-circuit the entire list of required children!

File: incubator/hnc/pkg/validators/hierarchy.go [hunk 5]
```diff
@@ -151,13 +166,32 @@ func (v *Hierarchy) checkForest(hc *api.HierarchyConfiguration) ([]authzReq, adm
...
+		}
+		if cns.Parent() != ns && (cns.Parent() != nil || cns.RequiredChildOf != ns.Name()) {
```
Comment (adrianludwin) [inline incubator/hnc/pkg/validators/hierarchy.go]: This might be easier to read in the reverse:

```
// If this is already a child, or is about to be, no problem
if cns.Parent() == ns || (cns.Parent() == nil && cns.RequiredChildOf == ns.Name()) {
  continue
}
```

File: incubator/hnc/pkg/validators/hierarchy.go (hunk 4 above)
Comment (yiqigao217) [reply incubator/hnc/pkg/validators/hierarchy.go]: Is it for in casing the concurrency issue when more than ONE requiredChild is added to the list?

Comment (adrianludwin) [reply incubator/hnc/pkg/validators/hierarchy.go]: I was just thinking "we should always make sure the entire list is valid" - that's always the way to think when writing a validator (or reconciler). But a concrete problem here might be if you manually edited the hc.yaml to add two children, one valid and one not.

Comment (yiqigao217) [reply incubator/hnc/pkg/validators/hierarchy.go]: sg.
